<?xml version="1.0" encoding="utf-8"?><Database Name="RealEstate" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Lenovo-PC\SQLEXPRESS;Initial Catalog=RealEstate;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RealEstateConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ad" Member="Ads">
    <Type Name="Ad">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KindID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TownID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="PriceCurrencyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deposit" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="DepositCurrencyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SalesmanID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OwnerName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="OwnerPhone" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="OwnerEmail" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DateAdded" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DateModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Seoword" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Ad_AdDetailByKind" Member="AdDetailByKinds" ThisKey="ID" OtherKey="AdID" Type="AdDetailByKind" />
      <Association Name="Ad_AdToPhoto" Member="AdToPhotos" ThisKey="ID" OtherKey="AdID" Type="AdToPhoto" />
      <Association Name="Category_Ad" Member="Category" ThisKey="CategoryID" OtherKey="ID" Type="Category" IsForeignKey="true" />
      <Association Name="City_Ad" Member="City" ThisKey="CityID" OtherKey="ID" Type="City" IsForeignKey="true" />
      <Association Name="Currency_Ad" Member="Currency" ThisKey="PriceCurrencyID" OtherKey="ID" Type="Currency" IsForeignKey="true" />
      <Association Name="Currency_Ad1" Member="Currency1" ThisKey="DepositCurrencyID" OtherKey="ID" Type="Currency" IsForeignKey="true" />
      <Association Name="District_Ad" Member="District" ThisKey="DistrictID" OtherKey="ID" Type="District" IsForeignKey="true" />
      <Association Name="Kind_Ad" Member="Kind" ThisKey="KindID" OtherKey="ID" Type="Kind" IsForeignKey="true" />
      <Association Name="Salesman_Ad" Member="Salesman" ThisKey="SalesmanID" OtherKey="ID" Type="Salesman" IsForeignKey="true" />
      <Association Name="Town_Ad" Member="Town" ThisKey="TownID" OtherKey="ID" Type="Town" IsForeignKey="true" />
      <Association Name="Type_Ad" Member="Type" ThisKey="TypeID" OtherKey="ID" Type="Type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdDetailByKind" Member="AdDetailByKinds">
    <Type Name="AdDetailByKind">
      <Column Name="AdID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KindDetailID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KindDetailMemberID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Ad_AdDetailByKind" Member="Ad" ThisKey="AdID" OtherKey="ID" Type="Ad" IsForeignKey="true" />
      <Association Name="KindDetailMember_AdDetailByKind" Member="KindDetailMember" ThisKey="KindDetailMemberID" OtherKey="ID" Type="KindDetailMember" IsForeignKey="true" />
      <Association Name="KindDetail_AdDetailByKind" Member="KindDetail" ThisKey="KindDetailID" OtherKey="ID" Type="KindDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdToPhoto" Member="AdToPhotos">
    <Type Name="AdToPhoto">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Photo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Ad_AdToPhoto" Member="Ad" ThisKey="AdID" OtherKey="ID" Type="Ad" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Category_Ad" Member="Ads" ThisKey="ID" OtherKey="CategoryID" Type="Ad" />
      <Association Name="Category_RequestMessage" Member="RequestMessages" ThisKey="ID" OtherKey="CategoryID" Type="RequestMessage" />
    </Type>
  </Table>
  <Table Name="dbo.City" Member="Cities">
    <Type Name="City">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="City_Ad" Member="Ads" ThisKey="ID" OtherKey="CityID" Type="Ad" />
      <Association Name="City_RequestMessage" Member="RequestMessages" ThisKey="ID" OtherKey="CityID" Type="RequestMessage" />
      <Association Name="City_Town" Member="Towns" ThisKey="ID" OtherKey="CityID" Type="Town" />
    </Type>
  </Table>
  <Table Name="dbo.ContactInformation" Member="ContactInformations">
    <Type Name="ContactInformation">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FixedPhone" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="MobilePhone" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ContactMessage" Member="ContactMessages">
    <Type Name="ContactMessage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsRead" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Currency" Member="Currencies">
    <Type Name="Currency">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Currency_Ad" Member="Ads" ThisKey="ID" OtherKey="PriceCurrencyID" Type="Ad" />
      <Association Name="Currency_Ad1" Member="Ads1" ThisKey="ID" OtherKey="DepositCurrencyID" Type="Ad" />
    </Type>
  </Table>
  <Table Name="dbo.DetailedInformationMessage" Member="DetailedInformationMessages">
    <Type Name="DetailedInformationMessage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AdID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsRead" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.District" Member="Districts">
    <Type Name="District">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TownID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="District_Ad" Member="Ads" ThisKey="ID" OtherKey="DistrictID" Type="Ad" />
      <Association Name="District_RequestMessage" Member="RequestMessages" ThisKey="ID" OtherKey="DistrictID" Type="RequestMessage" />
      <Association Name="Town_District" Member="Town" ThisKey="TownID" OtherKey="ID" Type="Town" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.InformationPage" Member="InformationPages">
    <Type Name="InformationPage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Text" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SeoWord" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.KindDetailMember" Member="KindDetailMembers">
    <Type Name="KindDetailMember">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KindDetailID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="KindDetailMember_AdDetailByKind" Member="AdDetailByKinds" ThisKey="ID" OtherKey="KindDetailMemberID" Type="AdDetailByKind" />
      <Association Name="KindDetail_KindDetailMember" Member="KindDetail" ThisKey="KindDetailID" OtherKey="ID" Type="KindDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KindDetail" Member="KindDetails">
    <Type Name="KindDetail">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KindID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ControlType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="KindDetail_AdDetailByKind" Member="AdDetailByKinds" ThisKey="ID" OtherKey="KindDetailID" Type="AdDetailByKind" />
      <Association Name="KindDetail_KindDetailMember" Member="KindDetailMembers" ThisKey="ID" OtherKey="KindDetailID" Type="KindDetailMember" />
      <Association Name="Kind_KindDetail" Member="Kind" ThisKey="KindID" OtherKey="ID" Type="Kind" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kind" Member="Kinds">
    <Type Name="Kind">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Kind_Ad" Member="Ads" ThisKey="ID" OtherKey="KindID" Type="Ad" />
      <Association Name="Kind_KindDetail" Member="KindDetails" ThisKey="ID" OtherKey="KindID" Type="KindDetail" />
      <Association Name="Kind_RequestMessage" Member="RequestMessages" ThisKey="ID" OtherKey="KindID" Type="RequestMessage" />
      <Association Name="Kind_Type" Member="Types" ThisKey="ID" OtherKey="KindID" Type="Type" />
    </Type>
  </Table>
  <Table Name="dbo.Language" Member="Languages">
    <Type Name="Language">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Flag" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.MetaTag" Member="MetaTags">
    <Type Name="MetaTag">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MetaDescription" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Keywords" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Module" Member="Modules">
    <Type Name="Module">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Page" Member="Pages">
    <Type Name="Page">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ControllerAndAction" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permission" Member="Permissions">
    <Type Name="Permission">
      <Column Name="UserGroupID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PageID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="UserGroup_Permission" Member="UserGroup" ThisKey="UserGroupID" OtherKey="ID" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RequestMessage" Member="RequestMessages">
    <Type Name="RequestMessage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="IP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsRead" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Message" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KindID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TownID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DistrictID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_RequestMessage" Member="Category" ThisKey="CategoryID" OtherKey="ID" Type="Category" IsForeignKey="true" />
      <Association Name="City_RequestMessage" Member="City" ThisKey="CityID" OtherKey="ID" Type="City" IsForeignKey="true" />
      <Association Name="District_RequestMessage" Member="District" ThisKey="DistrictID" OtherKey="ID" Type="District" IsForeignKey="true" />
      <Association Name="Kind_RequestMessage" Member="Kind" ThisKey="KindID" OtherKey="ID" Type="Kind" IsForeignKey="true" />
      <Association Name="Town_RequestMessage" Member="Town" ThisKey="TownID" OtherKey="ID" Type="Town" IsForeignKey="true" />
      <Association Name="Type_RequestMessage" Member="Type" ThisKey="TypeID" OtherKey="ID" Type="Type" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Salesman" Member="Salesmans">
    <Type Name="Salesman">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Salesman_Ad" Member="Ads" ThisKey="ID" OtherKey="SalesmanID" Type="Ad" />
    </Type>
  </Table>
  <Table Name="dbo.Town" Member="Towns">
    <Type Name="Town">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Town_Ad" Member="Ads" ThisKey="ID" OtherKey="TownID" Type="Ad" />
      <Association Name="Town_District" Member="Districts" ThisKey="ID" OtherKey="TownID" Type="District" />
      <Association Name="Town_RequestMessage" Member="RequestMessages" ThisKey="ID" OtherKey="TownID" Type="RequestMessage" />
      <Association Name="City_Town" Member="City" ThisKey="CityID" OtherKey="ID" Type="City" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Type" Member="Types">
    <Type Name="Type">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="KindID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Type_Ad" Member="Ads" ThisKey="ID" OtherKey="TypeID" Type="Ad" />
      <Association Name="Type_RequestMessage" Member="RequestMessages" ThisKey="ID" OtherKey="TypeID" Type="RequestMessage" />
      <Association Name="Kind_Type" Member="Kind" ThisKey="KindID" OtherKey="ID" Type="Kind" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserGroupID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UserGroup_User" Member="UserGroup" ThisKey="UserGroupID" OtherKey="ID" Type="UserGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserGroup" Member="UserGroups">
    <Type Name="UserGroup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="UserGroup_Permission" Member="Permissions" ThisKey="ID" OtherKey="UserGroupID" Type="Permission" />
      <Association Name="UserGroup_User" Member="Users" ThisKey="ID" OtherKey="UserGroupID" Type="User" />
    </Type>
  </Table>
</Database>