//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Kategorisi.
        /// </summary>
        internal static string AdCategoryIDDisplay {
            get {
                return ResourceManager.GetString("AdCategoryIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl.
        /// </summary>
        internal static string AdCityIDDisplay {
            get {
                return ResourceManager.GetString("AdCityIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan Oluşturma.
        /// </summary>
        internal static string AdCreateTitle {
            get {
                return ResourceManager.GetString("AdCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depozito.
        /// </summary>
        internal static string AdDepositDisplay {
            get {
                return ResourceManager.GetString("AdDepositDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Açıklama.
        /// </summary>
        internal static string AdDescriptionDisplay {
            get {
                return ResourceManager.GetString("AdDescriptionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Zorunlu.
        /// </summary>
        internal static string AdDescriptionRequired {
            get {
                return ResourceManager.GetString("AdDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan Detayları.
        /// </summary>
        internal static string AdDetailTitle {
            get {
                return ResourceManager.GetString("AdDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt.
        /// </summary>
        internal static string AdDistrictIDDisplay {
            get {
                return ResourceManager.GetString("AdDistrictIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan Düzenleme.
        /// </summary>
        internal static string AdEditTitle {
            get {
                return ResourceManager.GetString("AdEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Email Adresi.
        /// </summary>
        internal static string AdEmailInvalid {
            get {
                return ResourceManager.GetString("AdEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anahtar Kelimeler.
        /// </summary>
        internal static string AdKeywordsDisplay {
            get {
                return ResourceManager.GetString("AdKeywordsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü.
        /// </summary>
        internal static string AdKindIDDisplay {
            get {
                return ResourceManager.GetString("AdKindIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mevkii.
        /// </summary>
        internal static string AdLocationDisplay {
            get {
                return ResourceManager.GetString("AdLocationDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string AdLocationString {
            get {
                return ResourceManager.GetString("AdLocationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Açıklama.
        /// </summary>
        internal static string AdMetaDescriptionDisplay {
            get {
                return ResourceManager.GetString("AdMetaDescriptionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string AdOwnerEmailDisplay {
            get {
                return ResourceManager.GetString("AdOwnerEmailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string AdOwnerEmailString {
            get {
                return ResourceManager.GetString("AdOwnerEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Sahibi Adı Soyadı.
        /// </summary>
        internal static string AdOwnerNameDisplay {
            get {
                return ResourceManager.GetString("AdOwnerNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string AdOwnerNameString {
            get {
                return ResourceManager.GetString("AdOwnerNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Sahibi Telefonu.
        /// </summary>
        internal static string AdOwnerPhoneDisplay {
            get {
                return ResourceManager.GetString("AdOwnerPhoneDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string AdOwnerPhoneString {
            get {
                return ResourceManager.GetString("AdOwnerPhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiyat.
        /// </summary>
        internal static string AdPriceDisplay {
            get {
                return ResourceManager.GetString("AdPriceDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Sorumlusu.
        /// </summary>
        internal static string AdSalesmanIDDisplay {
            get {
                return ResourceManager.GetString("AdSalesmanIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seo Kelime.
        /// </summary>
        internal static string AdSeoWordDisplay {
            get {
                return ResourceManager.GetString("AdSeoWordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string AdSeoWordString {
            get {
                return ResourceManager.GetString("AdSeoWordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string AdStatusDisplay {
            get {
                return ResourceManager.GetString("AdStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan .
        /// </summary>
        internal static string AdTitle {
            get {
                return ResourceManager.GetString("AdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan Başlığı.
        /// </summary>
        internal static string AdTitleDisplay {
            get {
                return ResourceManager.GetString("AdTitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Zorunlu.
        /// </summary>
        internal static string AdTitleRequired {
            get {
                return ResourceManager.GetString("AdTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlan Resimleri.
        /// </summary>
        internal static string AdToPhotoTitle {
            get {
                return ResourceManager.GetString("AdToPhotoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Yükleme.
        /// </summary>
        internal static string AdToPhotoUploadTitle {
            get {
                return ResourceManager.GetString("AdToPhotoUploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe.
        /// </summary>
        internal static string AdTownIDDisplay {
            get {
                return ResourceManager.GetString("AdTownIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi.
        /// </summary>
        internal static string AdTypeIDDisplay {
            get {
                return ResourceManager.GetString("AdTypeIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri Dön.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İptal .
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Oluşturma.
        /// </summary>
        internal static string CategoryCreateTitle {
            get {
                return ResourceManager.GetString("CategoryCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Description.
        /// </summary>
        internal static string CategoryMetaDescriptionDisplay {
            get {
                return ResourceManager.GetString("CategoryMetaDescriptionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı .
        /// </summary>
        internal static string CategoryNameDisplay {
            get {
                return ResourceManager.GetString("CategoryNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı Boş Bırakılamaz.
        /// </summary>
        internal static string CategoryNameRequired {
            get {
                return ResourceManager.GetString("CategoryNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string CategoryNameString {
            get {
                return ResourceManager.GetString("CategoryNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Arama.
        /// </summary>
        internal static string CategorySearchTitle {
            get {
                return ResourceManager.GetString("CategorySearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Durumu .
        /// </summary>
        internal static string CategoryStatusDisplay {
            get {
                return ResourceManager.GetString("CategoryStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        internal static string CategoryTitle {
            get {
                return ResourceManager.GetString("CategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl Oluşturma.
        /// </summary>
        internal static string CityCreateTitle {
            get {
                return ResourceManager.GetString("CityCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl Adı .
        /// </summary>
        internal static string CityNameDisplay {
            get {
                return ResourceManager.GetString("CityNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl Adı Alanı Boş Bırakılamaz.
        /// </summary>
        internal static string CityNameRequired {
            get {
                return ResourceManager.GetString("CityNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl Adı Alanı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string CityNameString {
            get {
                return ResourceManager.GetString("CityNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl Arama.
        /// </summary>
        internal static string CitySearchTitle {
            get {
                return ResourceManager.GetString("CitySearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu .
        /// </summary>
        internal static string CityStatusDisplay {
            get {
                return ResourceManager.GetString("CityStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İller.
        /// </summary>
        internal static string CityTitle {
            get {
                return ResourceManager.GetString("CityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silmek İstediğinizden Eminmisiniz.
        /// </summary>
        internal static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string ContactInfoAddressDisplay {
            get {
                return ResourceManager.GetString("ContactInfoAddressDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string ContactInfoAddressString {
            get {
                return ResourceManager.GetString("ContactInfoAddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adı.
        /// </summary>
        internal static string ContactInfoCompanyNameDisplay {
            get {
                return ResourceManager.GetString("ContactInfoCompanyNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string ContactInfoCompanyNameString {
            get {
                return ResourceManager.GetString("ContactInfoCompanyNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ContactInfoEmailDisplay {
            get {
                return ResourceManager.GetString("ContactInfoEmailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Email Adresi.
        /// </summary>
        internal static string ContactInfoEmailInvalid {
            get {
                return ResourceManager.GetString("ContactInfoEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string ContactInfoEmailString {
            get {
                return ResourceManager.GetString("ContactInfoEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabit Telefon.
        /// </summary>
        internal static string ContactInfoFixedPhoneDisplay {
            get {
                return ResourceManager.GetString("ContactInfoFixedPhoneDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabit Telefon {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string ContactInfoFixedPhoneString {
            get {
                return ResourceManager.GetString("ContactInfoFixedPhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep Telefonu.
        /// </summary>
        internal static string ContactInfoMobilePhoneDisplay {
            get {
                return ResourceManager.GetString("ContactInfoMobilePhoneDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep Telefonu {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string ContactInfoMobilePhoneString {
            get {
                return ResourceManager.GetString("ContactInfoMobilePhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri Oluşturma.
        /// </summary>
        internal static string ContactInformationCreateTitle {
            get {
                return ResourceManager.GetString("ContactInformationCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Numarası.
        /// </summary>
        internal static string ContactInformationFaxDisplay {
            get {
                return ResourceManager.GetString("ContactInformationFaxDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Numarası {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string ContactInformationFaxString {
            get {
                return ResourceManager.GetString("ContactInformationFaxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri Arama.
        /// </summary>
        internal static string ContactInformationSearchTitle {
            get {
                return ResourceManager.GetString("ContactInformationSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim Bilgileri.
        /// </summary>
        internal static string ContactInformationTitle {
            get {
                return ResourceManager.GetString("ContactInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ContactInfoStatusDisplay {
            get {
                return ResourceManager.GetString("ContactInfoStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Kodu.
        /// </summary>
        internal static string CurrencyCodeDisplay {
            get {
                return ResourceManager.GetString("CurrencyCodeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Kodu Alanı Boş Bırakılamaz.
        /// </summary>
        internal static string CurrencyCodeRequired {
            get {
                return ResourceManager.GetString("CurrencyCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Kodu Alanı Enfazla {1} Karakterden Oluşur.
        /// </summary>
        internal static string CurrencyCodeString {
            get {
                return ResourceManager.GetString("CurrencyCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Oluşturma.
        /// </summary>
        internal static string CurrencyCreateTitle {
            get {
                return ResourceManager.GetString("CurrencyCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Adı.
        /// </summary>
        internal static string CurrencyNameDisplay {
            get {
                return ResourceManager.GetString("CurrencyNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Adı Alanı Boş Bırakılamaz.
        /// </summary>
        internal static string CurrencyNameRequired {
            get {
                return ResourceManager.GetString("CurrencyNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Adı Alanı Enfazla {1} Karakterden Oluşur.
        /// </summary>
        internal static string CurrencyNameString {
            get {
                return ResourceManager.GetString("CurrencyNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Arama.
        /// </summary>
        internal static string CurrencySearchTitle {
            get {
                return ResourceManager.GetString("CurrencySearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string CurrencyStatusDisplay {
            get {
                return ResourceManager.GetString("CurrencyStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Bilgileri.
        /// </summary>
        internal static string CurrencyTitle {
            get {
                return ResourceManager.GetString("CurrencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil .
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydı Sil ?.
        /// </summary>
        internal static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt Oluşturma.
        /// </summary>
        internal static string DistrictCreateTitle {
            get {
                return ResourceManager.GetString("DistrictCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt Adı .
        /// </summary>
        internal static string DistrictNameDisplay {
            get {
                return ResourceManager.GetString("DistrictNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt Adı Boş Bırakılamaz.
        /// </summary>
        internal static string DistrictNameRequired {
            get {
                return ResourceManager.GetString("DistrictNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt Adı Alanı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string DistrictNameString {
            get {
                return ResourceManager.GetString("DistrictNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt Arama.
        /// </summary>
        internal static string DistrictSearchTitle {
            get {
                return ResourceManager.GetString("DistrictSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu .
        /// </summary>
        internal static string DistrictStatusDisplay {
            get {
                return ResourceManager.GetString("DistrictStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semtler.
        /// </summary>
        internal static string DistrictTitle {
            get {
                return ResourceManager.GetString("DistrictTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe .
        /// </summary>
        internal static string DistrictTownIDDisplay {
            get {
                return ResourceManager.GetString("DistrictTownIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi Sayfası Oluşturma.
        /// </summary>
        internal static string InformationPageCreateTitle {
            get {
                return ResourceManager.GetString("InformationPageCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi Sayfası Oluşturma.
        /// </summary>
        internal static string InformationPageEditTitle {
            get {
                return ResourceManager.GetString("InformationPageEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Açıklama.
        /// </summary>
        internal static string InformationPageMetaDescriptionDisplay {
            get {
                return ResourceManager.GetString("InformationPageMetaDescriptionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Adı.
        /// </summary>
        internal static string InformationPageNameDisplay {
            get {
                return ResourceManager.GetString("InformationPageNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Boş Bırakılamaz.
        /// </summary>
        internal static string InformationPageNameRequired {
            get {
                return ResourceManager.GetString("InformationPageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string InformationPageNameString {
            get {
                return ResourceManager.GetString("InformationPageNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi Sayfası Arama.
        /// </summary>
        internal static string InformationPageSearchTitle {
            get {
                return ResourceManager.GetString("InformationPageSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seo Kelimesi.
        /// </summary>
        internal static string InformationPageSeoWordDisplay {
            get {
                return ResourceManager.GetString("InformationPageSeoWordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string InformationPageSeoWordString {
            get {
                return ResourceManager.GetString("InformationPageSeoWordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string InformationPageStatusDisplay {
            get {
                return ResourceManager.GetString("InformationPageStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Yazısı.
        /// </summary>
        internal static string InformationPageTextDisplay {
            get {
                return ResourceManager.GetString("InformationPageTextDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Boş Bırakılamaz.
        /// </summary>
        internal static string InformationPageTextRequired {
            get {
                return ResourceManager.GetString("InformationPageTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi Sayfaları.
        /// </summary>
        internal static string InformationPageTitle {
            get {
                return ResourceManager.GetString("InformationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Oluşturma.
        /// </summary>
        internal static string KindCreateTitle {
            get {
                return ResourceManager.GetString("KindCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Tipi .
        /// </summary>
        internal static string KindDetailControlTypeDisplay {
            get {
                return ResourceManager.GetString("KindDetailControlTypeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detayı Oluşturma.
        /// </summary>
        internal static string KindDetailCreateTitle {
            get {
                return ResourceManager.GetString("KindDetailCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü .
        /// </summary>
        internal static string KindDetailKindIDDisplay {
            get {
                return ResourceManager.GetString("KindDetailKindIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detay Elemanı Oluşturma.
        /// </summary>
        internal static string KindDetailMemberCreateTitle {
            get {
                return ResourceManager.GetString("KindDetailMemberCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detayı.
        /// </summary>
        internal static string KindDetailMemberKindDetailIDDisplay {
            get {
                return ResourceManager.GetString("KindDetailMemberKindDetailIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detay Elemanı.
        /// </summary>
        internal static string KindDetailMemberNameDisplay {
            get {
                return ResourceManager.GetString("KindDetailMemberNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detayı Boş Bırakılamaz.
        /// </summary>
        internal static string KindDetailMemberNameRequired {
            get {
                return ResourceManager.GetString("KindDetailMemberNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string KindDetailMemberNameString {
            get {
                return ResourceManager.GetString("KindDetailMemberNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detay Elemanı Arama.
        /// </summary>
        internal static string KindDetailMemberSearchTitle {
            get {
                return ResourceManager.GetString("KindDetailMemberSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string KindDetailMemberStatusDisplay {
            get {
                return ResourceManager.GetString("KindDetailMemberStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detay Elemanları.
        /// </summary>
        internal static string KindDetailMemberTitle {
            get {
                return ResourceManager.GetString("KindDetailMemberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detay Adı .
        /// </summary>
        internal static string KindDetailNameDisplay {
            get {
                return ResourceManager.GetString("KindDetailNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detay Adı Boş Bırakılamaz.
        /// </summary>
        internal static string KindDetailNameRequired {
            get {
                return ResourceManager.GetString("KindDetailNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detay Adı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string KindDetailNameString {
            get {
                return ResourceManager.GetString("KindDetailNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detayı Arama.
        /// </summary>
        internal static string KindDetailSearchTitle {
            get {
                return ResourceManager.GetString("KindDetailSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu .
        /// </summary>
        internal static string KindDetailStatusDisplay {
            get {
                return ResourceManager.GetString("KindDetailStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Detayları.
        /// </summary>
        internal static string KindDetailTitle {
            get {
                return ResourceManager.GetString("KindDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü .
        /// </summary>
        internal static string KindNameDisplay {
            get {
                return ResourceManager.GetString("KindNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Boş Bırakılamaz.
        /// </summary>
        internal static string KindNameRequired {
            get {
                return ResourceManager.GetString("KindNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü  {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string KindNameString {
            get {
                return ResourceManager.GetString("KindNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü Arama.
        /// </summary>
        internal static string KindSearchTitle {
            get {
                return ResourceManager.GetString("KindSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum .
        /// </summary>
        internal static string KindStatusDisplay {
            get {
                return ResourceManager.GetString("KindStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türleri.
        /// </summary>
        internal static string KindTitle {
            get {
                return ResourceManager.GetString("KindTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Kodu .
        /// </summary>
        internal static string LanguageCodeDisplay {
            get {
                return ResourceManager.GetString("LanguageCodeDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Kodu Boş Bırakılamaz.
        /// </summary>
        internal static string LanguageCodeRequired {
            get {
                return ResourceManager.GetString("LanguageCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Kodu {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string LanguageCodeString {
            get {
                return ResourceManager.GetString("LanguageCodeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Oluşturma.
        /// </summary>
        internal static string LanguageCreateTitle {
            get {
                return ResourceManager.GetString("LanguageCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya .
        /// </summary>
        internal static string LanguageFileNameDisplay {
            get {
                return ResourceManager.GetString("LanguageFileNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayrak .
        /// </summary>
        internal static string LanguageFlagDisplay {
            get {
                return ResourceManager.GetString("LanguageFlagDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Adı .
        /// </summary>
        internal static string LanguageNameDisplay {
            get {
                return ResourceManager.GetString("LanguageNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Adı Boş Bırakılamaz.
        /// </summary>
        internal static string LanguageNameRequired {
            get {
                return ResourceManager.GetString("LanguageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Adı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string LanguageNameString {
            get {
                return ResourceManager.GetString("LanguageNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Arama.
        /// </summary>
        internal static string LanguageSearchTitle {
            get {
                return ResourceManager.GetString("LanguageSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum .
        /// </summary>
        internal static string LanguageStatusDisplay {
            get {
                return ResourceManager.GetString("LanguageStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diller.
        /// </summary>
        internal static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay.
        /// </summary>
        internal static string ListAdDetail {
            get {
                return ResourceManager.GetString("ListAdDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resim Ekle.
        /// </summary>
        internal static string ListAdPicture {
            get {
                return ResourceManager.GetString("ListAdPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListAdStatus {
            get {
                return ResourceManager.GetString("ListAdStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        internal static string ListAdTitle {
            get {
                return ResourceManager.GetString("ListAdTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Adı.
        /// </summary>
        internal static string ListCategoryName {
            get {
                return ResourceManager.GetString("ListCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListCategoryStatus {
            get {
                return ResourceManager.GetString("ListCategoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl Adı.
        /// </summary>
        internal static string ListCityName {
            get {
                return ResourceManager.GetString("ListCityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListCityStatus {
            get {
                return ResourceManager.GetString("ListCityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçeler.
        /// </summary>
        internal static string ListCityTownList {
            get {
                return ResourceManager.GetString("ListCityTownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        internal static string ListContactInformationAddress {
            get {
                return ResourceManager.GetString("ListContactInformationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şirket Adı.
        /// </summary>
        internal static string ListContactInformationCompanyName {
            get {
                return ResourceManager.GetString("ListContactInformationCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ListContactInformationEmail {
            get {
                return ResourceManager.GetString("ListContactInformationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faks.
        /// </summary>
        internal static string ListContactInformationFax {
            get {
                return ResourceManager.GetString("ListContactInformationFax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sabit Telefon.
        /// </summary>
        internal static string ListContactInformationFixedPhone {
            get {
                return ResourceManager.GetString("ListContactInformationFixedPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cep Telefon.
        /// </summary>
        internal static string ListContactInformationMobilePhone {
            get {
                return ResourceManager.GetString("ListContactInformationMobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListContactInformationStatus {
            get {
                return ResourceManager.GetString("ListContactInformationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodu.
        /// </summary>
        internal static string ListCurrencyCode {
            get {
                return ResourceManager.GetString("ListCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Döviz Adı.
        /// </summary>
        internal static string ListCurrencyName {
            get {
                return ResourceManager.GetString("ListCurrencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu.
        /// </summary>
        internal static string ListCurrencyStatus {
            get {
                return ResourceManager.GetString("ListCurrencyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semt Adı.
        /// </summary>
        internal static string ListDistrictName {
            get {
                return ResourceManager.GetString("ListDistrictName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListDistrictStatus {
            get {
                return ResourceManager.GetString("ListDistrictStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe Adı.
        /// </summary>
        internal static string ListDistrictTownID {
            get {
                return ResourceManager.GetString("ListDistrictTownID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Adı.
        /// </summary>
        internal static string ListInformationPageName {
            get {
                return ResourceManager.GetString("ListInformationPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListInformationPageStatus {
            get {
                return ResourceManager.GetString("ListInformationPageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontrol Tipi .
        /// </summary>
        internal static string ListKindDetailControlType {
            get {
                return ResourceManager.GetString("ListKindDetailControlType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü .
        /// </summary>
        internal static string ListKindDetailKindID {
            get {
                return ResourceManager.GetString("ListKindDetailKindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detaylar.
        /// </summary>
        internal static string ListKindDetailList {
            get {
                return ResourceManager.GetString("ListKindDetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay Adı.
        /// </summary>
        internal static string ListKindDetailMemberKindDetailID {
            get {
                return ResourceManager.GetString("ListKindDetailMemberKindDetailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elemanlar.
        /// </summary>
        internal static string ListKindDetailMemberList {
            get {
                return ResourceManager.GetString("ListKindDetailMemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        internal static string ListKindDetailMemberName {
            get {
                return ResourceManager.GetString("ListKindDetailMemberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListKindDetailMemberStatus {
            get {
                return ResourceManager.GetString("ListKindDetailMemberStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detay Adı .
        /// </summary>
        internal static string ListKindDetailName {
            get {
                return ResourceManager.GetString("ListKindDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu .
        /// </summary>
        internal static string ListKindDetailStatus {
            get {
                return ResourceManager.GetString("ListKindDetailStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü.
        /// </summary>
        internal static string ListKindName {
            get {
                return ResourceManager.GetString("ListKindName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu .
        /// </summary>
        internal static string ListKindStatus {
            get {
                return ResourceManager.GetString("ListKindStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipler.
        /// </summary>
        internal static string ListKindTypeList {
            get {
                return ResourceManager.GetString("ListKindTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Kodu.
        /// </summary>
        internal static string ListLanguageCode {
            get {
                return ResourceManager.GetString("ListLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya Adı.
        /// </summary>
        internal static string ListLanguageFileName {
            get {
                return ResourceManager.GetString("ListLanguageFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bayrak.
        /// </summary>
        internal static string ListLanguageFlag {
            get {
                return ResourceManager.GetString("ListLanguageFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil Adı.
        /// </summary>
        internal static string ListLanguageName {
            get {
                return ResourceManager.GetString("ListLanguageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum .
        /// </summary>
        internal static string ListLanguageStatus {
            get {
                return ResourceManager.GetString("ListLanguageStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Değeri.
        /// </summary>
        internal static string ListPageControlAction {
            get {
                return ResourceManager.GetString("ListPageControlAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Adı.
        /// </summary>
        internal static string ListPageName {
            get {
                return ResourceManager.GetString("ListPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ListSalesmanEmail {
            get {
                return ResourceManager.GetString("ListSalesmanEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string ListSalesmanName {
            get {
                return ResourceManager.GetString("ListSalesmanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string ListSalesmanPhone {
            get {
                return ResourceManager.GetString("ListSalesmanPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListSalesmanStatus {
            get {
                return ResourceManager.GetString("ListSalesmanStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl Adı.
        /// </summary>
        internal static string ListTownCityID {
            get {
                return ResourceManager.GetString("ListTownCityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semtler.
        /// </summary>
        internal static string ListTownDistrictList {
            get {
                return ResourceManager.GetString("ListTownDistrictList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe Adı.
        /// </summary>
        internal static string ListTownName {
            get {
                return ResourceManager.GetString("ListTownName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListTownStatus {
            get {
                return ResourceManager.GetString("ListTownStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü.
        /// </summary>
        internal static string ListTypeKindID {
            get {
                return ResourceManager.GetString("ListTypeKindID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi.
        /// </summary>
        internal static string ListTypeName {
            get {
                return ResourceManager.GetString("ListTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListTypeStatus {
            get {
                return ResourceManager.GetString("ListTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string ListUserEmail {
            get {
                return ResourceManager.GetString("ListUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Grubu Adı.
        /// </summary>
        internal static string ListUserGroupName {
            get {
                return ResourceManager.GetString("ListUserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListUserGroupStatus {
            get {
                return ResourceManager.GetString("ListUserGroupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string ListUserName {
            get {
                return ResourceManager.GetString("ListUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string ListUserStatus {
            get {
                return ResourceManager.GetString("ListUserStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grup Adı.
        /// </summary>
        internal static string ListUserUserGroupName {
            get {
                return ResourceManager.GetString("ListUserUserGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string ListUserUserName {
            get {
                return ResourceManager.GetString("ListUserUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Açıklama.
        /// </summary>
        internal static string MetaTagdescDisplay {
            get {
                return ResourceManager.GetString("MetaTagdescDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Açıklama Alanı Boş Bırakılamaz.
        /// </summary>
        internal static string MetaTagDescRequired {
            get {
                return ResourceManager.GetString("MetaTagDescRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AnahtarKelime.
        /// </summary>
        internal static string MetaTagKeywordDisplay {
            get {
                return ResourceManager.GetString("MetaTagKeywordDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanahtar Kelime Alanı Boş Bırakılamaz.
        /// </summary>
        internal static string MetaTagKeywordRequired {
            get {
                return ResourceManager.GetString("MetaTagKeywordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meta Tag.
        /// </summary>
        internal static string MetaTagTitle {
            get {
                return ResourceManager.GetString("MetaTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        internal static string MetaTagTitleDisplay {
            get {
                return ResourceManager.GetString("MetaTagTitleDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık Alanı Boş Bırakılamaz.
        /// </summary>
        internal static string MetaTagTitleRequired {
            get {
                return ResourceManager.GetString("MetaTagTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Değeri.
        /// </summary>
        internal static string PageControlActionDisplay {
            get {
                return ResourceManager.GetString("PageControlActionDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Oluşturma.
        /// </summary>
        internal static string PageCreateTitle {
            get {
                return ResourceManager.GetString("PageCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Adı.
        /// </summary>
        internal static string PageNameDisplay {
            get {
                return ResourceManager.GetString("PageNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Adı Boş Bırakılamaz.
        /// </summary>
        internal static string PageNameRequired {
            get {
                return ResourceManager.GetString("PageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Adı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string PageNameString {
            get {
                return ResourceManager.GetString("PageNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Arama.
        /// </summary>
        internal static string PageSearchTitle {
            get {
                return ResourceManager.GetString("PageSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfalar.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen Seçiniz.
        /// </summary>
        internal static string PleaseSelect {
            get {
                return ResourceManager.GetString("PleaseSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Sorumlusu Oluşturma.
        /// </summary>
        internal static string SalesmanCreateTitle {
            get {
                return ResourceManager.GetString("SalesmanCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string SalesmanEmailDisplay {
            get {
                return ResourceManager.GetString("SalesmanEmailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz Email Adresi.
        /// </summary>
        internal static string SalesmanEmailInvalid {
            get {
                return ResourceManager.GetString("SalesmanEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alanı Boş Bırakılamaz.
        /// </summary>
        internal static string SalesmanEmailRequired {
            get {
                return ResourceManager.GetString("SalesmanEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Alanı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string SalesmanEmailString {
            get {
                return ResourceManager.GetString("SalesmanEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad .
        /// </summary>
        internal static string SalesmanNameDisplay {
            get {
                return ResourceManager.GetString("SalesmanNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad Boş Bırakılamaz.
        /// </summary>
        internal static string SalesmanNameRequired {
            get {
                return ResourceManager.GetString("SalesmanNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad Alanı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string SalesmanNameString {
            get {
                return ResourceManager.GetString("SalesmanNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon no.
        /// </summary>
        internal static string SalesmanPhoneDisplay {
            get {
                return ResourceManager.GetString("SalesmanPhoneDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon no Boş Bırakılamaz.
        /// </summary>
        internal static string SalesmanPhoneRequired {
            get {
                return ResourceManager.GetString("SalesmanPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon Alanı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string SalesmanPhoneString {
            get {
                return ResourceManager.GetString("SalesmanPhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Sorumlusu Arama.
        /// </summary>
        internal static string SalesmanSearchTitle {
            get {
                return ResourceManager.GetString("SalesmanSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satış Sorumluları.
        /// </summary>
        internal static string SalesmanTitle {
            get {
                return ResourceManager.GetString("SalesmanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaydet .
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu.
        /// </summary>
        internal static string SlaesmanStatusDisplay {
            get {
                return ResourceManager.GetString("SlaesmanStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem Başarılı .
        /// </summary>
        internal static string Successfull {
            get {
                return ResourceManager.GetString("Successfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İl .
        /// </summary>
        internal static string TownCityIDDisplay {
            get {
                return ResourceManager.GetString("TownCityIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe Oluşturma.
        /// </summary>
        internal static string TownCreateTitle {
            get {
                return ResourceManager.GetString("TownCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe Adı .
        /// </summary>
        internal static string TownNameDisplay {
            get {
                return ResourceManager.GetString("TownNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe Adı Boş Bırakılamaz.
        /// </summary>
        internal static string TownNameRequired {
            get {
                return ResourceManager.GetString("TownNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe Adı Alanı {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string TownNameString {
            get {
                return ResourceManager.GetString("TownNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçe Arama.
        /// </summary>
        internal static string TownSearchTitle {
            get {
                return ResourceManager.GetString("TownSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu .
        /// </summary>
        internal static string TownStatusDisplay {
            get {
                return ResourceManager.GetString("TownStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İlçeler.
        /// </summary>
        internal static string TownTitle {
            get {
                return ResourceManager.GetString("TownTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi Oluşturma.
        /// </summary>
        internal static string TypeCreateTitle {
            get {
                return ResourceManager.GetString("TypeCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Türü.
        /// </summary>
        internal static string TypeKindIDDisplay {
            get {
                return ResourceManager.GetString("TypeKindIDDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi.
        /// </summary>
        internal static string TypeNameDisplay {
            get {
                return ResourceManager.GetString("TypeNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi Boş Geçilemez.
        /// </summary>
        internal static string TypeNameRequired {
            get {
                return ResourceManager.GetString("TypeNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string TypeNameString {
            get {
                return ResourceManager.GetString("TypeNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi Arama.
        /// </summary>
        internal static string TypeSearchTitle {
            get {
                return ResourceManager.GetString("TypeSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durumu.
        /// </summary>
        internal static string TypeStatusDisplay {
            get {
                return ResourceManager.GetString("TypeStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emlak Tipi.
        /// </summary>
        internal static string TypeTitle {
            get {
                return ResourceManager.GetString("TypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifreler Uyuşmuyor Tekrar Deneyiniz.
        /// </summary>
        internal static string UserConfirmPass {
            get {
                return ResourceManager.GetString("UserConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre Doğrula.
        /// </summary>
        internal static string UserConfirmPassDisplay {
            get {
                return ResourceManager.GetString("UserConfirmPassDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Boş Bırakılamaz.
        /// </summary>
        internal static string UserConfirmPassRequired {
            get {
                return ResourceManager.GetString("UserConfirmPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string UserConfirmPassString {
            get {
                return ResourceManager.GetString("UserConfirmPassString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Oluşturma.
        /// </summary>
        internal static string UserCreateTitle {
            get {
                return ResourceManager.GetString("UserCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserEmailDisplay {
            get {
                return ResourceManager.GetString("UserEmailDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Boş Bırakılamaz.
        /// </summary>
        internal static string UserEmailRequired {
            get {
                return ResourceManager.GetString("UserEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string UserEmailString {
            get {
                return ResourceManager.GetString("UserEmailString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Grubu Oluşturma.
        /// </summary>
        internal static string UserGroupCreateTitle {
            get {
                return ResourceManager.GetString("UserGroupCreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Grubu Adı.
        /// </summary>
        internal static string UserGroupNameDisplay {
            get {
                return ResourceManager.GetString("UserGroupNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Grubu Adı Boş Geçilemez.
        /// </summary>
        internal static string UserGroupNameRequired {
            get {
                return ResourceManager.GetString("UserGroupNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string UserGroupNameString {
            get {
                return ResourceManager.GetString("UserGroupNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sayfa Listesi.
        /// </summary>
        internal static string UserGroupPageList {
            get {
                return ResourceManager.GetString("UserGroupPageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Grubu Arama.
        /// </summary>
        internal static string UserGroupSearchTitle {
            get {
                return ResourceManager.GetString("UserGroupSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string UserGroupStatusDisplay {
            get {
                return ResourceManager.GetString("UserGroupStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Grupları.
        /// </summary>
        internal static string UserGroupTitle {
            get {
                return ResourceManager.GetString("UserGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Soyad.
        /// </summary>
        internal static string UserNameDisplay {
            get {
                return ResourceManager.GetString("UserNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Boş Bırakılamaz.
        /// </summary>
        internal static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string UserNameString {
            get {
                return ResourceManager.GetString("UserNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        internal static string UserPassDisplay {
            get {
                return ResourceManager.GetString("UserPassDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Boş Bırakılamaz.
        /// </summary>
        internal static string UserPassRequired {
            get {
                return ResourceManager.GetString("UserPassRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string UserPassString {
            get {
                return ResourceManager.GetString("UserPassString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        internal static string UserPhoneDisplay {
            get {
                return ResourceManager.GetString("UserPhoneDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string UserPhoneString {
            get {
                return ResourceManager.GetString("UserPhoneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Arama.
        /// </summary>
        internal static string UserSearchTitle {
            get {
                return ResourceManager.GetString("UserSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durum.
        /// </summary>
        internal static string UserStatusDisplay {
            get {
                return ResourceManager.GetString("UserStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcılar.
        /// </summary>
        internal static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Grubu.
        /// </summary>
        internal static string UserUserGroupDisplay {
            get {
                return ResourceManager.GetString("UserUserGroupDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string UserUserNameDisplay {
            get {
                return ResourceManager.GetString("UserUserNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alan Boş Bırakılamaz.
        /// </summary>
        internal static string UserUserNameRequired {
            get {
                return ResourceManager.GetString("UserUserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} Karakterden Fazla Olamaz.
        /// </summary>
        internal static string UserUserNameString {
            get {
                return ResourceManager.GetString("UserUserNameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Büyüt.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
